In [33]:
import pandas as pd
import re
import numpy as np

In [437]:
JapanNuclearWater = pd.read_csv('../data/Twitter/twitter.csv')
#Fukushima = pd.read_csv('../data/Fukushima.csv')
# JapanNuclearWater = pd.read_csv('../data/Weibo/weibo.csv')
# JapanNuclearWater = df
df = JapanNuclearWater
df.head()

,user_id,created_at,screen_name,text,location
0,9.160000e+17,18/4/2021 11:51,XGuoforWaterloo,@JohnOCAP Don't forget the #Fukushima #Nuclear...,"Kitchener, Ontario"
1,9.160000e+17,17/4/2021 11:49,XGuoforWaterloo,@rafaelmgrossi @iaeaorg The attitude of the US...,"Kitchener, Ontario"
2,1.463413e+09,18/4/2021 11:44,Aroguden,#SouthKorea raised concerns over #Japan's deci...,Barquisimeto-Venezuela
3,1.463413e+09,13/4/2021 11:32,Aroguden,#Japan will release more than a million tonnes...,Barquisimeto-Venezuela
4,1.463413e+09,14/4/2021 9:38,Aroguden,#SouthKorea aims to fight #Japan's #Fukushima ...,Barquisimeto-Venezuela

In [441]:
# #df.dropna(inplace = True)
# #China df
# China1 = df[JapanNuclearWater['location'] == 'Beijing, China']
# China2 = df[JapanNuclearWater['location'] == 'Beijing']
# China3 = df[JapanNuclearWater['location'] == '‰∏≠Âçé‰∫∫Ê∞ëÂÖ±ÂíåÂõΩ']
# China4 = df[JapanNuclearWater['location'] == 'Peoplestr\'s Republic of China']
# China5 = df[JapanNuclearWater['location'] == 'Âåó‰∫¨, ‰∏≠Âçé‰∫∫Ê∞ëÂÖ±ÂíåÂõΩ']
# China6 = df[JapanNuclearWater['location'] == 'Hangzhou | Zhejiang | PRC üá®üá≥']
# China7 = df[JapanNuclearWater['location'] == 'China']



# #Japan df
# Japan1 = df[JapanNuclearWater['location'] == 'Tokyo, Japan']
# Japan2 = df[JapanNuclearWater['location'] == 'Tokyo']
# Japan3 = df[JapanNuclearWater['location'] == 'Japan']

# #USA df
# USA1 = df[JapanNuclearWater['location'] == 'United States']
# USA2 = df[JapanNuclearWater['location'] == 'USA']
# USA3 = df[JapanNuclearWater['location'] == 'Washington, DC']

# #England df
# England1 = df[JapanNuclearWater['location'] == 'London']
# England2 = df[JapanNuclearWater['location'] == 'London, England']

# #India df
# India = df[JapanNuclearWater['location'] == 'India']
HongKong = df[JapanNuclearWater['location'] == 'Hong Kong']

In [439]:
# China = pd.concat([England1,England2])
# China.head()

In [442]:
HongKong.to_csv("../data/HongKongTwist.csv",index=False,sep=',', encoding='utf-8')

In [435]:
region = pd.read_csv('../data/RegionRanking.csv')
# s = JapanNuclearWater['location'].value_counts().head(100)
# df=s.to_frame()
# df
# df.reset_index(inplace = True)
# #user_id	created_at	screen_name	text	JapanNuclearWater_tweet_df.location
# df.rename(columns={'index':'region'
#                                }, inplace = True)
# df.head()
region['region'].tolist()

['Beijing, China',
 'United States',
 'Earth',
 'Tokyo, Japan',
 'Beijing',
 'Hong Kong',
 'London',
 'USA',
 'Tokyo',
 '‰∏≠Âçé‰∫∫Ê∞ëÂÖ±ÂíåÂõΩ',
 'India',
 "People's Republic of China",
 'Âåó‰∫¨, ‰∏≠Âçé‰∫∫Ê∞ëÂÖ±ÂíåÂõΩ',
 'Censored',
 'London, England',
 'Hangzhou | Zhejiang | PRC üá®üá≥',
 'Washington, DC',
 'China',
 '127.0.0.0',
 'Japan',
 'Global',
 'Ontario, Canada',
 'New Delhi, India',
 'Wien, √ñsterreich',
 'Los Angeles, CA',
 'California, USA',
 'France',
 'ÎåÄÌïúÎØºÍµ≠ ÏÑúÏö∏',
 'Seoul, Korea ',
 'Canada',
 'Singapore',
 'Tokyo‚û°Kumamoto,Japan',
 'City of London, London',
 'UK',
 'Germany',
 'Èñ¢Êù±Âú∞Êñπ JAPAN      Ê∏¨ÂÆöÂô®ÔºöDC100',
 'onmyoji',
 'New York, USA',
 'Seoul, Korea',
 'Malaysia',
 'Hong Kong is part of China',
 'Headquartered in Beijing, PRC',
 '„Åæ„Åª„Çç„Å∞ „ÇÑ„Åæ„ÅÆ„Åπ„ÅÆ„Åø„Å°',
 'Beijing, CHINA',
 'Australia',
 'Shanghai',
 'Dublin City, Ireland',
 'Worldwide',
 'United Kingdom',
 'ITALY',
 'Jakarta, Indonesia',
 'New York, NY',
 'üåç',
 'The United Kingdom ',
 'Vienna, Austria',
 'Jamaica- Trinidad &Tobago',
 'Dhaka, Bangladesh',
 'üá¶üá∫ Australia  ',
 'Lucknow Canttonment Zone, Luck',
 'Chicago, IL',
 'London, UK',
 'Mumbai, India',
 'Berlin',
 'Shenzhen',
 'Berlin, Germany',
 'XINJIANG',
 'Paris, France',
 'San Francisco, CA',
 'Amsterdam, The Netherlands',
 'Êµ∑ÂçÉÂ±±ÂçÉ ',
 'Shanghai China',
 'Melbourne, Victoria',
 'Auckland',
 'Brampton, Ontario',
 'Denmark',
 'Âè∞ÁÅ£',
 'ÊÅ∂‰∫∫Ë∞∑',
 'Whitehouse, OH',
 'NIBIRU PLANET X',
 'Barquisimeto-Venezuela',
 '‰∏äÊµ∑, ‰∏≠Âçé‰∫∫Ê∞ëÂÖ±ÂíåÂõΩ',
 'N√ºrnberg, Bayern',
 'Hong Kong, China',
 'England',
 'Geneva, Switzerland',
 "At Gold's Gym making gains.",
 'Seoul, South Korea',
 'mars',
 'Alpha Centauri  ',
 'new york',
 'Karimnagar, India',
 'My dog ‚ùÑüêï‚ùÑ @SnowdogChampion',
 'Ahmedabad',
 'South Africa',
 'Canterbury Region, New Zealand',
 'tokyo',
 'Ireland',
 'Birmingham, England',
 'Berlin, Deutschland',
 'Midland, Texas']

In [303]:
Weibo1 = pd.read_csv('../data/Weibo/ÂæÆÂçö2021-04-12.csv')
Weibo2 = pd.read_csv('../data/Weibo/ÂæÆÂçö2021-04-13.csv')
Weibo3 = pd.read_csv('../data/Weibo/ÂæÆÂçö2021-04-14.csv')
Weibo4 = pd.read_csv('../data/Weibo/ÂæÆÂçö2021-04-15.csv')
Weibo5 = pd.read_csv('../data/Weibo/ÂæÆÂçö2021-04-16.csv')
Weibo6 = pd.read_csv('../data/Weibo/ÂæÆÂçö2021-04-17.csv', sep='\t', encoding='utf-8', lineterminator='\n')
Weibo7 = pd.read_csv('../data/Weibo/ÂæÆÂçö2021-04-18.csv', sep='\t', encoding='utf-8', lineterminator='\n')
Weibo = pd.concat([Weibo,Weibo7])
Weibo.shape

(6390, 12)

In [324]:
Weibo.to_csv("../data/Weibo/weibo.csv",index=False,sep=',', encoding='utf-8')
Weibo = pd.read_csv('../data/Weibo.csv')
Weibo.shape

(6390, 12)

In [31]:
twitter1 = pd.read_csv('../data/Twitter/Fukushima.csv')
twitter2 = pd.read_csv('../data/Twitter/NuclearWaste.csv')
twitter3 = pd.read_csv('../data/Twitter/JapanNuclearWater.csv')
twitter4 = pd.read_csv('../data/Twitter/Japannuclearwastewater.csv')
twitter = pd.concat([twitter,twitter4])
twitter.head()

,user_id,created_at,screen_name,text,location
0,9.156680e+17,2021-04-18 11:51:30,XGuoforWaterloo,@JohnOCAP Don't forget the #Fukushima #Nuclear...,"Kitchener, Ontario"
1,9.156680e+17,2021-04-17 11:49:52,XGuoforWaterloo,@rafaelmgrossi @iaeaorg The attitude of the US...,"Kitchener, Ontario"
2,1.463413e+09,2021-04-18 11:44:34,Aroguden,#SouthKorea raised concerns over #Japan's deci...,Barquisimeto-Venezuela
3,1.463413e+09,2021-04-13 11:32:23,Aroguden,#Japan will release more than a million tonnes...,Barquisimeto-Venezuela
4,1.463413e+09,2021-04-14 09:38:19,Aroguden,#SouthKorea aims to fight #Japan's #Fukushima ...,Barquisimeto-Venezuela

In [32]:
twitter.to_csv("../data/twitter.csv",index=False,sep=',', encoding='utf-8')

- Áî®Ê≠£ÂàôË°®ËææÂºèÊèêÂèñ@mentionÁî®Êà∑

In [326]:
def retrieveMention(df):
    df['new']=''
    
    reg=r"@.*? "
    for index, row in df.iterrows():
        df['new'][index]=';'.join(re.findall(reg, row['text']))
    return df

- create user_mention dataframe

In [327]:
def user_mention_df(dataset):
    userNameL = []
    mentionNameL = []
    lenOfmention = 0
    for index, row in dataset.iterrows():
        if len(dataset['new'].str.split(' ;', 100).tolist()[index]) == 1: # Â¶ÇÊûú‰∏Ä‰∏™Áî®Êà∑@Ë∂ÖËøá‰∏Ä‰∏™ÈÇ£‰πàÂ∞±Êää‰ªñ@ÁöÑÁî®Êà∑‰∏Ä‰∏™‰∏™ÈöîÁ¶ªÂØπÂ∫îÁî®Êà∑ÂàÜÂà´ÊîæÂú®‰∏ÄË°å
            userName = dataset['screen_name'].tolist()[index]
            mentionName = dataset['new'].tolist()[index] #Êú¨Êù•Â∞±@Èáå‰∏Ä‰∏™Áî®Êà∑ÔºåÂ∞±‰∏çÈúÄË¶ÅÈöîÁ¶ª‰∫ÜÔºå‰∏çÁÑ∂‰ºöÂá∫Áé∞list‰∏≠Êúâlist
            userNameL.append(userName)
            mentionNameL.append(mentionName)    
        else:
            for lenOfmention in range(len(dataset['new'].str.split(' ;', 100).tolist()[index])):
                userName = dataset['screen_name'].tolist()[index]
                mentionName = dataset['new'].str.split(' ;', 100).tolist()[index][lenOfmention]
                userNameL.append(userName)
                mentionNameL.append(mentionName)
    
    #List to dataframe
    c={"userName" : userNameL,
    "mentionName" : mentionNameL}
    
    data=pd.DataFrame(c)
    
    print('the lengh of user: ', len(userNameL))
    print('the lengh of mention:', len(mentionNameL))
    
    return data

In [334]:
JapanNuclearWater = retrieveMention(JapanNuclearWater)

<ipython-input-326-a23953796e4c>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['new'][index]=';'.join(re.findall(reg, row['text']))

In [335]:
JapanNuclearWater.to_csv("../data/JapanNuclearWaterUserMention.csv",index=False,sep=',', encoding='utf-8')
JapanNuclearWaterUserMention = pd.read_csv('../data/JapanNuclearWaterUserMention.csv')
JapanNuclearWaterUserMention = JapanNuclearWaterUserMention.dropna(subset = ['new'])
JapanNuclearWaterUserMention = JapanNuclearWaterUserMention.reset_index(drop = True)
df = user_mention_df(JapanNuclearWaterUserMention)

the lengh of user:  350
the lengh of mention: 350

In [336]:
df = user_mention_df(JapanNuclearWaterUserMention)
df

the lengh of user:  350
the lengh of mention: 350

           userName mentionName
0           hikaruÂß¨    @Mr_Âá°ÂÖàÁîü
1               Èõ®Êº´ÂÄæ        @‰∏ñÈù¢
2            Aecho9   @ÁéãÂ≠üÊ∫êdudu
3            Aecho9   @ÁéãÂ≠üÊ∫êdudu
4          NBAshley   @‰∏âÁª¥Âú∞ÂõæÁúã‰∏ñÁïå
..              ...         ...
345             Ê≤∏ÂÖîÂÖî       @ÂæÆ‰∏¢¬†
346            ‰∏ÄÁ¢óÊó†Èáè        @‰∏ñÈù¢
347           Â§ßËë±È±ºÂ≠êÈÖ±   @R1SE-ÂßöÁêõ
348           Ë•øÈùíÊ£ÄÂØüÂÆò       @ËøôËßÜÈ¢ë
349  ÊúâÂøÉ‰∫∫18266528387       @‰∫∫Ê∞ëÁΩë

[350 rows x 2 columns]

In [337]:
df.to_csv("../data/WeiboUserMention.csv",index=False,sep=',', encoding='utf-8')

## Rename columns

In [121]:
Fukushima = pd.read_csv('../data/weibo.csv')
Fukushima.head()

,Âçö‰∏ª,id,Êó∂Èó¥,Êù•Ê∫ê,Êî∂Ëóè,ËΩ¨Âèë,ËØÑËÆ∫,ÁÇπËµû,ËâæÁâπ,Ê†áÁ≠æ,ÂÜÖÂÆπ
0,2345ËêΩËã±Áº§Á∫∑,6628711225,04Êúà12Êó• 22:59,OPPOÊô∫ËÉΩÊâãÊú∫,NaN,NaN,NaN,1.0,NaN,#Êó•Êú¨Ê†∏Â∫üÊ∞¥ÂèØËá¥ÁôåËá¥Áï∏Ëá¥Á™ÅÂèò#,ËÅîÂêàÂõΩÂë¢ÔºüËøô‰πàÂ§ßÁöÑ‰∫ãÈÉΩ‰∏çÂèëÂ£∞ÁöÑÂêóÔºüÊàëÂ§©ËôΩÁÑ∂Êàë‰∏çÊòØÂåªÂ≠¶ÁîüÔºå‰ΩÜÊòØÂàáÂ∞îËØ∫Ë¥ùÂà©Á∫™ÂΩïÁâáÁúãÂæóÊàëÊØõÈ™®ÊÇöÁÑ∂Ôºå...
1,ËÑ∏Èïø‰πüÂè´ÁâπÈïøbaiÁîü,2962593974,04Êúà12Êó• 22:59,OPPO R9s,NaN,NaN,NaN,NaN,NaN,#Êó•Êú¨Ê†∏Â∫üÊ∞¥ÂèØËá¥ÁôåËá¥Áï∏Ëá¥Á™ÅÂèò#,"Êó•Êú¨Ê†∏Â∫üÊ∞¥‰∏ÄÊó¶ÊéíÂÖ•Â§™Âπ≥Ê¥ã‰∏≠Âç±ÂÆ≥ÊúâÂ§öÂ§ß,‰ª•ÂêéÊµ∑È≤úËøòÊúâ‰∫∫Êï¢ÂêÉÂêó?‚ÄúÂì•ÊñØÊãâ‚Äù‰ºöÂõ†Ê≠§Âá∫Áé∞ÂêóÔºü Ôøºmo..."
2,Â∞èÊ°ÉÁ∫¢Êü≥Áªø,2149115373,04Êúà12Êó• 22:59,Âçé‰∏∫P8,NaN,NaN,NaN,NaN,NaN,#Êó•Êú¨Ê†∏Â∫üÊ∞¥ÂèØËá¥ÁôåËá¥Áï∏Ëá¥Á™ÅÂèò#,„Äê‰∏ìÂÆ∂Ôºö„Äë4Êúà9Êó•ÔºåÊó•Êú¨ÊîøÂ∫úÂü∫Êú¨ÂÜ≥ÂÆöÂ∞ÜÁ¶èÂ≤õÊ†∏Ê±°Ê∞¥ÊéíÂÖ•Â§ßÊµ∑„ÄÇ12Êó•ÔºåÊó•Êú¨È¶ñÁõ∏ËèÖ‰πâ‰ºüË°®Á§∫ÔºåËß£ÂÜ≥‰∏ú...
3,ËãπÊûúÊü†Ê™¨ÂàÆÊ≤πÊ±§,2635391551,04Êúà12Êó• 22:59,AndroidÂÆ¢Êà∑Á´Ø,NaN,NaN,NaN,NaN,NaN,#Êó•Êú¨Ê†∏Â∫üÊ∞¥ÂèØËá¥ÁôåËá¥Áï∏Ëá¥Á™ÅÂèò#,‰ªäÊó•Êó•Êú¨È¶ñÁõ∏ËèÖ‰πâ‰ºüÂÜçÊ¨°Ë°®Á§∫ÔºåÁ¶èÂ≤õÊ†∏Ê±°Ê∞¥ÊéíÂÖ•Â§ßÊµ∑Â∑≤Áªè‰∏çËÉΩÊé®Ëøü‰∫ÜÂæ∑ÂõΩÁöÑÊµ∑Ê¥ãÁßëÂ≠¶Á†îÁ©∂Êú∫ÊûÑÁöÑËÆ°ÁÆóÊòæÁ§∫...
4,Èô≥ÊØÖYiChen,2389546112,04Êúà12Êó• 22:59,Â∞èÁ±≥5s ÊãçÁÖßÈªëÁßëÊäÄ,NaN,NaN,NaN,NaN,NaN,#Êó•Êú¨Ê†∏Â∫üÊ∞¥ÂèØËá¥ÁôåËá¥Áï∏Ëá¥Á™ÅÂèò#,„Äê‰∏ìÂÆ∂Ôºö„Äë4Êúà9Êó•ÔºåÊó•Êú¨ÊîøÂ∫úÂü∫Êú¨ÂÜ≥ÂÆöÂ∞ÜÁ¶èÂ≤õÊ†∏Ê±°Ê∞¥ÊéíÂÖ•Â§ßÊµ∑„ÄÇ12Êó•ÔºåÊó•Êú¨È¶ñÁõ∏ËèÖ‰πâ‰ºüË°®Á§∫ÔºåËß£ÂÜ≥‰∏ú...

In [332]:
#user_id	created_at	screen_name	text	JapanNuclearWater_tweet_df.location
JapanNuclearWater.rename(columns={'Âçö‰∏ª':'screen_name'
                               }, inplace = True)
# JapanNuclearWater.drop(columns=["Âçö‰∏ª,id,Êó∂Èó¥,Êù•Ê∫ê,Êî∂Ëóè,ËΩ¨Âèë,ËØÑËÆ∫,ÁÇπËµû,ËâæÁâπ,Ê†áÁ≠æ,ÂÜÖÂÆπ\r"], inplace = True)

In [333]:
JapanNuclearWater.head()

,screen_name,id,Êó∂Èó¥,Êù•Ê∫ê,Êî∂Ëóè,ËΩ¨Âèë,ËØÑËÆ∫,ÁÇπËµû,ËâæÁâπ,Ê†áÁ≠æ,text,new
0,2345ËêΩËã±Áº§Á∫∑,6.628711e+09,04Êúà12Êó• 22:59,OPPOÊô∫ËÉΩÊâãÊú∫,NaN,NaN,NaN,1.0,NaN,#Êó•Êú¨Ê†∏Â∫üÊ∞¥ÂèØËá¥ÁôåËá¥Áï∏Ëá¥Á™ÅÂèò#,ËÅîÂêàÂõΩÂë¢ÔºüËøô‰πàÂ§ßÁöÑ‰∫ãÈÉΩ‰∏çÂèëÂ£∞ÁöÑÂêóÔºüÊàëÂ§©ËôΩÁÑ∂Êàë‰∏çÊòØÂåªÂ≠¶ÁîüÔºå‰ΩÜÊòØÂàáÂ∞îËØ∫Ë¥ùÂà©Á∫™ÂΩïÁâáÁúãÂæóÊàëÊØõÈ™®ÊÇöÁÑ∂Ôºå...,
1,ËÑ∏Èïø‰πüÂè´ÁâπÈïøbaiÁîü,2.962594e+09,04Êúà12Êó• 22:59,OPPO R9s,NaN,NaN,NaN,NaN,NaN,#Êó•Êú¨Ê†∏Â∫üÊ∞¥ÂèØËá¥ÁôåËá¥Áï∏Ëá¥Á™ÅÂèò#,"Êó•Êú¨Ê†∏Â∫üÊ∞¥‰∏ÄÊó¶ÊéíÂÖ•Â§™Âπ≥Ê¥ã‰∏≠Âç±ÂÆ≥ÊúâÂ§öÂ§ß,‰ª•ÂêéÊµ∑È≤úËøòÊúâ‰∫∫Êï¢ÂêÉÂêó?‚ÄúÂì•ÊñØÊãâ‚Äù‰ºöÂõ†Ê≠§Âá∫Áé∞ÂêóÔºü Ôøºmo...",
2,Â∞èÊ°ÉÁ∫¢Êü≥Áªø,2.149115e+09,04Êúà12Êó• 22:59,Âçé‰∏∫P8,NaN,NaN,NaN,NaN,NaN,#Êó•Êú¨Ê†∏Â∫üÊ∞¥ÂèØËá¥ÁôåËá¥Áï∏Ëá¥Á™ÅÂèò#,„Äê‰∏ìÂÆ∂Ôºö„Äë4Êúà9Êó•ÔºåÊó•Êú¨ÊîøÂ∫úÂü∫Êú¨ÂÜ≥ÂÆöÂ∞ÜÁ¶èÂ≤õÊ†∏Ê±°Ê∞¥ÊéíÂÖ•Â§ßÊµ∑„ÄÇ12Êó•ÔºåÊó•Êú¨È¶ñÁõ∏ËèÖ‰πâ‰ºüË°®Á§∫ÔºåËß£ÂÜ≥‰∏ú...,
3,ËãπÊûúÊü†Ê™¨ÂàÆÊ≤πÊ±§,2.635392e+09,04Êúà12Êó• 22:59,AndroidÂÆ¢Êà∑Á´Ø,NaN,NaN,NaN,NaN,NaN,#Êó•Êú¨Ê†∏Â∫üÊ∞¥ÂèØËá¥ÁôåËá¥Áï∏Ëá¥Á™ÅÂèò#,‰ªäÊó•Êó•Êú¨È¶ñÁõ∏ËèÖ‰πâ‰ºüÂÜçÊ¨°Ë°®Á§∫ÔºåÁ¶èÂ≤õÊ†∏Ê±°Ê∞¥ÊéíÂÖ•Â§ßÊµ∑Â∑≤Áªè‰∏çËÉΩÊé®Ëøü‰∫ÜÂæ∑ÂõΩÁöÑÊµ∑Ê¥ãÁßëÂ≠¶Á†îÁ©∂Êú∫ÊûÑÁöÑËÆ°ÁÆóÊòæÁ§∫...,
4,Èô≥ÊØÖYiChen,2.389546e+09,04Êúà12Êó• 22:59,Â∞èÁ±≥5s ÊãçÁÖßÈªëÁßëÊäÄ,NaN,NaN,NaN,NaN,NaN,#Êó•Êú¨Ê†∏Â∫üÊ∞¥ÂèØËá¥ÁôåËá¥Áï∏Ëá¥Á™ÅÂèò#,„Äê‰∏ìÂÆ∂Ôºö„Äë4Êúà9Êó•ÔºåÊó•Êú¨ÊîøÂ∫úÂü∫Êú¨ÂÜ≥ÂÆöÂ∞ÜÁ¶èÂ≤õÊ†∏Ê±°Ê∞¥ÊéíÂÖ•Â§ßÊµ∑„ÄÇ12Êó•ÔºåÊó•Êú¨È¶ñÁõ∏ËèÖ‰πâ‰ºüË°®Á§∫ÔºåËß£ÂÜ≥‰∏ú...,

In [716]:
df.to_csv("../data/Fukushima.csv",index=False,sep=',', encoding='utf-8')